// Part 2 and 3 about a really dumb investment strategy
//======================================================


//two test portfolios

val blchip_portfolio = List("GOOG", "AAPL", "MSFT", "IBM", "FB", "AMZN", "BIDU")
val rstate_portfolio = List("PLD", "PSA", "AMT", "AIV", "AVB", "BXP", "CCI",
  "DLR", "EQIX", "EQR", "ESS", "EXR", "FRT", "HCP")


// (1) The function below takes a stock symbol and a year as arguments.
//     It should read the corresponding CSV-file and reads the January 
//     data from the given year. The data should be collected in a list of
//     strings for each line in the CSV-file.

import io.Source
import scala.util._

def get_january_data(symbol: String, year: Int) : List[String] = {
  val file = Source.fromFile(symbol.toUpperCase() + ".csv")
  val list = file.getLines.toList.filter(_.startsWith(year.toString + "-01"))
  file.close()
  list
}


// (2) From the output of the get_january_data function, the next function 
//     should extract the first line (if it exists) and the corresponding
//     first trading price in that year with type Option[Double]. If no line 
//     is generated by get_january_data then the result is None; Some if 
//     there is a price.


def get_first_price(symbol: String, year: Int) : Option[Double] = {
  val january_data = get_january_data(symbol,year)
  if(january_data.nonEmpty){
    val line = january_data.head.split(",").map(_.trim)
    Some(line{1}.toDouble)
  }
  else None
}


// (3) Complete the function below that obtains all first prices
//     for the stock symbols from a portfolio (list of strings) and 
//     for the given range of years. The inner lists are for the
//     stock symbols and the outer list for the years.


def get_prices_year(portfolio: List[String], year: Int) : List[Option[Double]] = {
  portfolio.map(get_first_price(_,year))
}

def get_prices(portfolio: List[String], years: Range) : List[List[Option[Double]]] = {
  years.map(get_prices_year(portfolio,_)).toList
}



//==============================================
// Do not change anything below, unless you want 
// to submit the file for the advanced part 3!
//==============================================


// (4) The function below calculates the change factor (delta) between
//     a price in year n and a price in year n + 1. 

def get_delta(price_old: Option[Double], price_new: Option[Double]) : Option[Double] = {
  if(price_old.isEmpty || price_new.isEmpty) None
  else Some((price_new.get - price_old.get) / price_old.get)
}


// (5) The next function calculates all change factors for all prices (from a 
//     portfolio). The input to this function are the nested lists created by 
//     get_prices above.

def portfolio_deltas(prevVals:  List[Option[Double]], currVals: List[Option[Double]]) : List[Option[Double]] = {
  for ((prev,curr) <- prevVals zip currVals) yield get_delta(prev,curr)
}

def get_deltas(data: List[List[Option[Double]]]) :  List[List[Option[Double]]] = {
  for ((prevVals,currVals) <- data zip data.drop(1)) yield portfolio_deltas(prevVals,currVals)
}


// (6) Write a function that given change factors, a starting balance and an index,
//     calculates the yearly yield, i.e. new balance, according to our dumb investment 
//     strategy. Index points to a year in the data list.

def yearly_yield(data: List[List[Option[Double]]], balance: Long, index: Int) : Long = {
  val flattened_year_change = data(index).flatten
  balance + (flattened_year_change.sum / flattened_year_change.size * balance).toLong
}


// (7) Write a function compound_yield that calculates the overall balance for a 
//     range of years where in each year the yearly profit is compounded to the new 
//     balances and then re-invested into our portfolio. For this use the function and 
//     results generated under (6). The function investment calls compound_yield
//     with the appropriate deltas and the first index.

def compound_yield(data: List[List[Option[Double]]], balance: Long, index: Int) : Long = {
  if(index < data.size) compound_yield(data, yearly_yield(data, balance, index), index + 1)
  else balance
}

def investment(portfolio: List[String], years: Range, start_balance: Long) : Long = {
  val deltas = get_deltas(get_prices(portfolio, years))
  compound_yield(deltas, start_balance, 0)
}




//Test cases for the two portfolios given above

//println("Real data: " + investment(rstate_portfolio, 1978 to 2018, 100))
//println("Blue data: " + investment(blchip_portfolio, 1978 to 2018, 100))

// Trigger advanced tests
